# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FRPPixels' do

pod 'ReactiveCocoa', '2.5'
pod 'libextobjc', '0.4.1'
pod '500px-iOS-api', '1.0.5'
pod 'SVProgressHUD', '1.1.3'

end

