# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ITWReactiveCocoaTest' do

pod 'ReactiveCocoa', '~> 2.2.4'
pod 'AFNetworking', '~> 2.6.3'

end

