# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TWMasonryDemo' do

pod 'Masonry','1.0.0'
pod 'HandyFrame'

end

