# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FRPPlayground' do

pod 'RXCollections',	'~> 1.0'
pod 'ReactiveCocoa',	'~> 2.5'

end

